### ISSUE TITLE
no error on invalid values in select

### ISSUE THREAD

**Issue by eroux** [buda-base/blmp-client#35]
in https://editor.bdrc.io/edit/bdr:MW30118/bds:InstanceShape there are two values in selects that are invalid according the shacl shape: one title type and the script (in the "physical feature" group). They should be marked as errors so that the user knows they need to be changed

**Comment by berger-n** [comment]
fixed: https://editor.bdrc.io/edit/bdr:MW30118/bds:InstanceShape

![Kazam_screencast_00116 mp4](https://user-images.githubusercontent.com/33383857/181505426-bf306431-576e-41a9-9042-a5dbb214662e.gif)

note there's also an invalid id type:

![image](https://user-images.githubusercontent.com/33383857/181505550-8c907952-f7ef-4f4b-b6d3-1a0fb8374652.png)

where another id namely https://ldspdi.bdrc.io/resource/PL480.ttl needs a `prefLabel` instead of a `label`

**Comment by eroux** [comment]
thanks a lot! The label thing is a bit strange though, `bdr:OclcControlNumber` (right above in the list) only has a `rdfs:label`

**Comment by berger-n** [comment]
indeed! fixed (use identifier without prefix when no `prefLabel` available):

![image](https://user-images.githubusercontent.com/33383857/181576622-e15570a7-ba64-4303-ace1-c4168c8ffc40.png)
