### ISSUE TITLE
integer GIS coordinates

### ISSUE THREAD

**Issue by eroux** [buda-base/blmp-client#43]
When I go to https://editor.bdrc.io/edit/bdr:G1563/bds:PlaceShape and try to save, the editor sends GIS coordinates as floats instead of strings. This is probably because they are like that in the original file, but the issue is that now we can't save anything... and strangely this also happens when I select other (very close) coordinates. Is it possible to force the placeLat and placeLong fields to be strings? (I know there is some amount of code for these fields). Perhaps in general we should enforce the datatype from the shape, even if the value doesn't match

**Comment by berger-n** [comment]
I can't reproduce [when creating a new Place]
just created a place and saved coordinates, we already send strings to server:
```
(...)
bdr:G1NB12
    bdo:placeLat "89.1";
    bdo:placeLong "17.1";
(...)
```
same in the case of integer values:
```
    bdo:placeLat "89";
    bdo:placeLong "17";
```
[edit: can reproduce in the case of your specific example, investigating]

**Comment by eroux** [comment]
yes, the issue is when the editor gets integer values from editserv

**Comment by berger-n** [comment]
seems to be ok now: https://editor.bdrc.io/edit/bdr:G1563/bds:PlaceShape

(it loads strings from server because I was able to save, but first it had to check if inferred datatype was different from property datatype and update it accordingly, see [commit](https://github.com/buda-base/blmp-client/commit/d757cefb0fa81c0c4b89827598d35a2becccd884))

you might want to try it on another example if any?

**Comment by eroux** [comment]
thanks a lot! That's fine
