### ISSUE TITLE
add ability to modify another user profile (for admins only)

### ISSUE THREAD

**Issue by eroux** [buda-base/blmp-client#47]
It should be possible for admins to modify a user profile, but when typing a user profile (starting with an `U`) in the Load entity box I'm getting the error message "no shape found for..."

**Comment by berger-n** [comment]
done: https://editor.bdrc.io/
- when logged in as a member of the admin group:
(I've been able to add a profile picture and save, then remove it and save):

![image](https://github.com/buda-base/blmp-client/assets/33383857/2f43e4f1-fd77-43e5-8d1f-010d1c76b1e8)

---

- otherwise (403):

![image](https://github.com/buda-base/blmp-client/assets/33383857/6262e834-437a-46a2-91b3-4fe0aecc6402)

**Comment by eroux** [comment]
fantastic, thanks!
